map_type: costmap

robot_radius: 0.215
footprint_padding: 0.0
transform_tolerance: 0.2

obstacle_layer:
 enabled: true
 obstacle_range: 20.0
 raytrace_range: 20.0
 inflation_radius: 0.0
 track_unknown_space: false
 combination_method: 1

 observation_sources: laser_scan_front laser_scan_back
 
 laser_scan_front: {
   sensor_frame: lidar_front_real,
   data_type: LaserScan,
   topic: /scan_front,
   expected_update_rate: 0.5,
   observation_persistence: 0.0,
   marking: true,
   clearing: true,
   min_obstacle_height: -0.1,
   max_obstacle_height: 2.0}
 
 laser_scan_back: {
   sensor_frame: lidar_back_real,
   data_type: LaserScan,
   topic: /scan_back,
   expected_update_rate: 0.5,
   observation_persistence: 0.0,
   marking: true,
   clearing: true, 
   min_obstacle_height: -0.1, 
   max_obstacle_height: 2.0}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.30  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled: true
  map_topic: "/map_obs"
