TebLocalPlannerROS:
   
 # Trajectory
 teb_autosize: True
 dt_ref: 0.2
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 10.0
 feasibility_check_no_poses: 50
 global_plan_viapoint_sep: 0.3
    
 # Robot
         
 max_vel_x: 1.5
 max_vel_x_backwards: 1.5
 max_vel_y: 1.5
 max_vel_theta: 4.5
 acc_lim_x: 0.25
 acc_lim_y: 0.25
 acc_lim_theta: 0.5
 min_turning_radius: 0.0 # omni-drive robot (can turn on place!)

 footprint_model:
   type: "line"
   line_start: [-0.12, 0.0]
   line_end: [0.12, 0.0]

 # GoalTolerance
    
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.05
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.215 #0.24 This value must also include our robot radius, since footprint_model is set to "point".
 inflation_dist: 1.0
 dynamic_obstacle_inflation_dist: 1.0
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 5.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull" 
 costmap_converter_spin_thread: True
 costmap_converter_rate: 10
 obstacle_association_force_inclusion_factor: 1.5
 obstacle_association_cutoff_factor: 3

 # Costmap converter | concave polygon
 costmap_converter/CostmapToPolygonsDBSConcaveHull:
  cluster_max_distance: 0.3
  cluster_min_pts: 2
  cluster_max_pts: 10
  convex_hull_min_pt_separation: 0.1
  concave_hull_depth: 2.0

 # Optimization  
 no_inner_iterations: 5.0
 no_outer_iterations: 10.0
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_y: 2
 weight_max_vel_theta: 2
 weight_acc_lim_x: 1
 weight_acc_lim_y: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
 weight_kinematics_forward_drive: 0.2
 weight_kinematics_turning_radius: 0
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_viapoint: 1.0

 # Homotopy Class Planner

 enable_homotopy_class_planning: False
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
